version: "3"
services:
  soga_tnl:
    image: vaxilu/soga:latest
    restart: on-failure
    network_mode: host
    container_name: soga_tnl
    environment:
      type: v2board
      server_type: ss
      node_id: 214
      soga_key: A8DVWC16ayRIJV5aDwznkVzYftrFVeKU
      api: webapi
      webapi_url: https://www.eton.club/
      webapi_key: 314314314314314314
      default_dns: 8.8.8.8
      dns_cache_time: 10
      dns_strategy: ipv4_first
      proxy_protocol: 'true'
      udp_proxy_protocol: 'true'
      force_close_ssl: 'false'
      forbidden_bit_torrent: 'true'
      log_level: debug
      tfo: 'true'
      forbidden_ports: 22,3389
    volumes:
      - "/etc/soga/:/etc/soga/"

  soga_iplc:
    image: vaxilu/soga:latest
    restart: on-failure
    network_mode: host
    container_name: soga_iplc
    environment:
      type: v2board
      server_type: ss
      node_id: 215
      soga_key: A8DVWC16ayRIJV5aDwznkVzYftrFVeKU
      api: webapi
      webapi_url: https://www.eton.club/
      webapi_key: 314314314314314314
      default_dns: 8.8.8.8
      dns_cache_time: 10
      dns_strategy: ipv4_first
      proxy_protocol: 'true'
      udp_proxy_protocol: 'true'
      force_close_ssl: 'false'
      forbidden_bit_torrent: 'true'
      log_level: debug
      tfo: 'true'
      forbidden_ports: 22,3389
    volumes:
      - "/etc/soga/:/etc/soga/"

  soga_udpn:
    image: vaxilu/soga:latest
    restart: on-failure
    network_mode: host
    container_name: soga_udpn
    environment:
      type: v2board
      server_type: ss
      node_id: 529
      soga_key: A8DVWC16ayRIJV5aDwznkVzYftrFVeKU
      api: webapi
      webapi_url: https://www.eton.club/
      webapi_key: 314314314314314314
      default_dns: 8.8.8.8
      dns_cache_time: 10
      dns_strategy: ipv4_first
      proxy_protocol: 'true'
      udp_proxy_protocol: 'true'
      force_close_ssl: 'false'
      forbidden_bit_torrent: 'true'
      log_level: debug
      tfo: 'true'
      forbidden_ports: 22,3389
    volumes:
      - "/etc/soga/:/etc/soga/"
